export const ActionTypes = {
    SELECTED_MOVIE: 'SELECTED_MOVIE',
    REMOVE_SELECTED_MOVIE: 'REMOVE_SELECTED_MOVIE',
    SET_MOVIES: 'SET_MOVIES',
    REMOVE_SET_MOVIES: 'REMOVE_SET_MOVIES',
    SET_PAGE_NUM: 'SET_PAGE_NUM',
    INCREASE_PAGE_NUM: 'INCREASE_PAGE_NUM',
    DECREASE_PAGE_NUM: 'DECREASE_PAGE_NUM',
}